server:
  port: 8082

spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer.rmq
      routing-key:
        producer: rk.queue.producer.rmq
      deadletter:
        producer: dl.queue.producer.rmq
